# Generated by Django 4.0.2 on 2022-02-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cached', '0002_alter_expense_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
