# Generated by Django 4.0.2 on 2022-02-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cached', '0003_alter_goal_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
