# Generated by Django 4.0.2 on 2022-02-10 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cached', '0006_alter_goal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='user_identifier',
            field=models.IntegerField(null=True, unique_for_date='month'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL),
        ),
    ]
