# Generated by Django 4.0.2 on 2022-02-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cached', '0007_goal_user_identifier_alter_goal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='user_identifier',
            field=models.IntegerField(unique_for_date='month'),
        ),
    ]
